#!/usr/bin/env bash
set -e

if [ ! -f ./node_modules/@thecotne/tasker/tasker-core ]; then
  yarn
fi

source ./node_modules/@thecotne/tasker/tasker-core

IMAGE_NAME=${PWD##*/}

function start { # start mining
  node ./src/miner.js
}

function docker-start { # start mining in docker container
  docker build -t $IMAGE_NAME .
  docker run $IMAGE_NAME
}

function docker-ci-test { # docker ci test
  docker build -t $IMAGE_NAME .
  docker run $IMAGE_NAME /bin/sh -c "./tasker start & sleep 30"
}

function docker-stop-containers { # stop all docker containers
  docker stop $(docker ps -a -q)
}

function docker-destroy-containers { # destroy all docker containers
  docker rm $(docker ps -a -q)
}

function docker-destroy-images { # destroy all docker images
  docker rmi $(docker images -q)
}

function docker-destroy-all { # destory all docker images and containers
  docker-stop-containers
  docker-destroy-containers
  docker-destroy-images
}

_bootstrap "${@}"
